set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(DEFINED ENV{LLVM_MINGW_ROOT} AND NOT "$ENV{LLVM_MINGW_ROOT}" STREQUAL "")
    set(LLVM_MINGW_ROOT "$ENV{LLVM_MINGW_ROOT}")
else()
    get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
    set(LLVM_MINGW_ROOT "${PROJECT_ROOT}/toolchains/llvm-mingw")
endif()

set(LLVM_MINGW_BIN "${LLVM_MINGW_ROOT}/bin")
set(LLVM_MINGW_SYSROOT "${LLVM_MINGW_ROOT}/x86_64-w64-mingw32")
set(LLVM_MINGW_GENERIC_ROOT "${LLVM_MINGW_ROOT}/generic-w64-mingw32")

find_program(LLVM_MINGW_CLANG x86_64-w64-mingw32-clang PATHS "${LLVM_MINGW_BIN}" NO_DEFAULT_PATH REQUIRED)
find_program(LLVM_MINGW_CLANGXX x86_64-w64-mingw32-clang++ PATHS "${LLVM_MINGW_BIN}" NO_DEFAULT_PATH REQUIRED)
find_program(LLVM_MINGW_WINDRES llvm-rc PATHS "${LLVM_MINGW_BIN}" NO_DEFAULT_PATH)

set(CMAKE_C_COMPILER "${LLVM_MINGW_CLANG}")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW_CLANGXX}")

if(LLVM_MINGW_WINDRES)
    set(CMAKE_RC_COMPILER "${LLVM_MINGW_WINDRES}")
endif()

set(CMAKE_FIND_ROOT_PATH "${LLVM_MINGW_ROOT}" "${LLVM_MINGW_SYSROOT}" "${LLVM_MINGW_GENERIC_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
