set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(MINGW_GCC x86_64-w64-mingw32-gcc REQUIRED)
find_program(MINGW_GXX x86_64-w64-mingw32-g++ REQUIRED)
find_program(MINGW_WINDRES x86_64-w64-mingw32-windres)

set(CMAKE_C_COMPILER "${MINGW_GCC}")
set(CMAKE_CXX_COMPILER "${MINGW_GXX}")

if(MINGW_WINDRES)
    set(CMAKE_RC_COMPILER "${MINGW_WINDRES}")
endif()

set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32 /usr/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
